name: proarea_catsapp
description: A new Flutter project.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: '>=2.19.6 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  flutter_bloc: ^8.1.2
  equatable: ^2.0.5
  get_it: ^7.3.0
  dio: ^5.1.1
  retrofit: ^4.0.1
  logger: ^1.3.0
  json_annotation: ^4.8.0
  cached_network_image: ^3.2.3
  intl: ^0.18.1
  hive_flutter: ^1.1.0
  hive_generator: ^2.0.0
  lottie: ^2.3.2
  font_awesome_flutter: ^10.4.0
  sprintf: ^7.0.0
  flutter_native_splash: ^2.2.19

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner: ^2.3.3
  injectable: ^2.1.1
  injectable_generator: ^2.1.5
  retrofit_generator: ^6.0.0+3
  json_serializable: ^6.6.1
  flutter_launcher_icons: ^0.13.1
  mockito: ^5.4.0

flutter:

  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/
    

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
flutter_launcher_icons:
  android: "ic_launcher"
  ios: true
  image_path: "assets/app_icon_1024.png"
  min_sdk_android: 21 # android min sdk min:16, default 21
  web:
    generate: false
    image_path: "path/to/image.png"
    background_color: "#hexcode"
    theme_color: "#hexcode"
  windows:
    generate: false
    image_path: "path/to/image.png"
    icon_size: 48 # min:48, max:256, default: 48
  macos:
    generate: false
    image_path: "path/to/image.png"



flutter_native_splash:
  android: true
  ios: true
  color: "#ffffff"
  image: "assets/app_icon_1024.png"
  android_12:
    color: "#ffffff"
